### ISSUE TITLE
Back trace with the 2.0.6 version

### ISSUE THREAD

**Issue by subramanyamVemu** [ofa/django-bouncy#26]
ERROR Internal Server Error: /sns/bouncy/
Traceback (most recent call last):
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django_bouncy/views.py", line 128, in endpoint
    return process_message(message, data)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django_bouncy/views.py", line 149, in process_message
    return process_delivery(message, notification)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django_bouncy/views.py", line 258, in process_delivery
    smtp_response=delivery['smtpResponse']
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/cacheops/transaction.py", line 99, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mode/.virtualenvs/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: smallint out of range

Request repr(): 
<WSGIRequest
path:/sns/bouncy/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTENT_LENGTH': '1798',
 'CONTENT_TYPE': 'text/plain; charset=UTF-8',
 u'CSRF_COOKIE': u'2k2vPHO2TLL873PbxgGdkoPHfp2mSt4x',
 'HTTP_ACCEPT_ENCODING': 'gzip,deflate',
 'HTTP_HOST': 'www.xxxxxxx.com',
 'HTTP_USER_AGENT': 'Amazon Simple Notification Service Agent',
 'HTTP_X_AMZ_SNS_MESSAGE_ID': '0e4a3c2a-d20e-5eb1-aebf-6fcf127b5c88',
 'HTTP_X_AMZ_SNS_MESSAGE_TYPE': 'Notification',
 'HTTP_X_AMZ_SNS_SUBSCRIPTION_ARN': 'arn:aws:sns:us-east-1:XXXXXXXXXXX:XXXXXXXXXXXXXXX:f8d4b071-3058-45ca-b46a-33957d0c1d11',
 'HTTP_X_AMZ_SNS_TOPIC_ARN': 'arn:aws:sns:us-east-1:XXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXX',
 'HTTP_X_FORWARDED_FOR': '72.21.217.152',
 'PATH_INFO': u'/sns/bouncy/',
 'QUERY_STRING': '',
 'RAW_URI': '/sns/bouncy/',
 'REMOTE_ADDR': '',
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'www.xxxxxxx.com',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gunicorn/19.7.1',
 'gunicorn.socket': <socket._socketobject object at 0x7f07d266f590>,
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f07d77cae10>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gunicorn.http.body.Body object at 0x7f07d7f74310>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

**Comment by cleder** [comment]
fixed with #21

**Comment by thenewguy** [comment]
@cleder any chance of a new release to pypi?
