### ISSUE TITLE
DataError: value too long for type character varying(150)

### ISSUE THREAD

**Issue by gio82** [ofa/django-bouncy#4]
I guess some of the fields are too short. I'm not able to find which one though.

```
Internal Server Error: /bouncy/
Traceback (most recent call last):
 File "python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
   return view_func(*args, **kwargs)
 File "python2.7/site-packages/django_bouncy/views.py", line 123, in endpoint
   return process_message(message, data)
 File "python2.7/site-packages/django_bouncy/views.py", line 142, in process_message
   return process_bounce(message, notification)
 File "python2.7/site-packages/django_bouncy/views.py", line 170, in process_bounce
   diagnostic_code=recipient.get('diagnosticCode')
 File "python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
   return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "python2.7/site-packages/django/db/models/query.py", line 348, in create
   obj.save(force_insert=True, using=self.db)
 File "python2.7/site-packages/django/db/models/base.py", line 710, in save
   force_update=force_update, update_fields=update_fields)
 File "site-packages/django/db/models/base.py", line 738, in save_base
   updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
 File "python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
   result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
 File "python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
   using=using, raw=raw)
 File "python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
   return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "python2.7/site-packages/django/db/models/query.py", line 920, in _insert
   return query.get_compiler(using=using).execute_sql(return_id)
 File "python2.7/site-packages/django/db/models/sql/compiler.py", line 971, in execute_sql
   cursor.execute(sql, params)
 File "python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
   return self.cursor.execute(sql, params)
 File "python2.7/site-packages/django/db/utils.py", line 97, in __exit__
   six.reraise(dj_exc_type, dj_exc_value, traceback)
 File "python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
   return self.cursor.execute(sql, params)
DataError: value too long for type character varying(150)
```

**Comment by gio82** [comment]
As a blind fix at the moment I changed the `max_length=250` to the fields that had `150`.
